# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  machine:
    services:
      - mysql
  database:
    pre:
      # https://gist.github.com/mahemoff/54b31e272421472d4fb6
      # installing mysql 5.6 (5.5 is installed by default)
      - export DEBIAN_FRONTEND=noninteractive
        && sudo apt-get -y remove mysql-server && sudo apt-get -y autoremove
        && sudo apt-get -y install software-properties-common
        && sudo apt-add-repository -y 'deb http://ppa.launchpad.net/ondrej/mysql-experimental/ubuntu precise main'
        && sudo apt-get update
        && sudo apt-get -y install mysql-server
      - echo -e "[mysqld]\ninnodb_file_format = Barracuda\ninnodb_large_prefix = 1" | sudo sh -c "cat >> /etc/mysql/my.cnf"
      - sudo cat /etc/mysql/my.cnf
      - sudo service mysql restart
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test
